/**
 * ARTIK Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cloud.artik.model




case class DeviceType (
  /* Device Type ID. */
  id: String,
/* Unique Name. */
  uniqueName: String,
/* Latest Manifest version. */
  latestVersion: Integer,
lastUpdated: Long,
/* Name. */
  name: String,
/* Description. */
  description: String,
/* User ID. */
  uid: String,
/* Organization ID. */
  oid: String,
/* Uses Cloud Connectors SDK */
  hasCloudConnector: Boolean,
/* Approval status. */
  approved: Boolean,
/* Published status. */
  published: Boolean,
/* Protected status. */
  _protected: Boolean,
/* In Store. */
  inStore: Boolean,
/* Does the current user own a device of this device type */
  ownedByCurrentUser: Boolean,
/* Tags */
  tags: List[Tag],
/* Require Secure Device Registration (SDR) Protocol. */
  rsp: Boolean,
/* Issuer Distinguished Name (Used in SDR) */
  issuerDn: String,
/* Vendor ID. (Used in SDR) */
  vid: String)
