/**
 * ARTIK Cloud API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cloud.artik.model




case class ExportRequestInfo (
  /* Add header to csv format */
  csvHeaders: Boolean,
/* Timestamp of latest message (in milliseconds since epoch). */
  endDate: Long,
/* Format of the export. */
  format: String,
/* Ascending or descending sort order. */
  order: String,
/* Source Device IDs being searched for messages (Comma-separated for multiple Device IDs). */
  sdids: String,
/* Source Device Type IDs being searched for messages (Comma-separated for multiple Device Type IDs). */
  sdtids: String,
/* Timestamp of earliest message (in milliseconds since epoch). */
  startDate: Long,
/* Trial ID being searched for messages. */
  trialId: String,
/* Owner's user IDs being searched for messages (Comma-separated for multiple User IDs). */
  uids: String,
/* URL added to successful email message. */
  url: String)
